### ISSUE TITLE
Expanding number of rooms

### ISSUE THREAD

**Issue by wowpin** [Frimkron/mud-pi#4]
Hi,

When thinking about expanding to a larger number of rooms, one will eventually run into a limit - no two rooms can be named the same. 

Example:
It would be impossible to have two rooms named "Corridor" (imagine a long corridor consisting of multiple rooms).

I'm thinking about introducing another parameter to the room structure - roomID. Perhaps exits should link to unique room IDs rather unique room names?

**Comment by Frimkron** [comment]
That's a good point. I kept the identifier for the room the same as the displayed name, just for simplicity. 

An improvement when expanding on it for your own project would indeed be to use a separate id to uniquely identify rooms with the same name. Another way of looking at it is that you could keep the string-based name for identifying the room internally ("corridor1", "corridor2"), and add a separate "display name" field that the user sees ("Corridor").

I think I'll add a note about it in the code and leave it as an exercise for the reader :)
